FROM node:18

# 1. Устанавливаем зависимости
WORKDIR /tmp
COPY package*.json ./
RUN npm install

# 2. Копируем весь проект
WORKDIR /app
COPY . .

# 3. Запускаем Next.js в dev-режиме
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
